<%@ Page Title="Equipment" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Equipment.aspx.cs" Inherits="Makerspace.Equipment" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
       <h1>Makerspace Equipment</h1>
    </div>

    <asp:UpdatePanel runat="server">
        <ContentTemplate>
            <div style="text-align:center">
                <asp:ListView ID="categoryList" runat="server" DataSourceID="MakerspaceDB" >
                    <ItemTemplate>
                        <b style="font-size: large; font-style: normal">
                            <asp:Button  ID="cat_btn" runat="server" Text='<%# Eval("catName")%>'>   
                            </asp:Button> 
                        </b>
                    </ItemTemplate>
                    <ItemSeparatorTemplate>  |  </ItemSeparatorTemplate>
                </asp:ListView>
                <asp:SqlDataSource ID="MakerspaceDB" runat="server" ConnectionString="<%$ ConnectionStrings:MakerspaceDBConnectionString %>" SelectCommand="SELECT [catName] FROM [Category]"></asp:SqlDataSource>
            </div>
            

          

            <div style="text-align:center">
                <asp:RadioButton ID="NameBtn" runat="server" GroupName="EquipmentSearch" Text="By Name"  Checked="true"/>
                <asp:RadioButton ID="FunctionBtn" runat="server" GroupName="EquipmentSearch" Text="By Function" />
                <asp:RadioButton ID="ECodeBtn" runat="server" GroupName="EquipmentSearch" Text="By Equipment Code"/>
                <asp:RadioButton ID="LocBtn" runat="server" GroupName="EquipmentSearch" Text="By Location Name" />
                <asp:RadioButton ID="LocCodeBtn" runat="server" GroupName="EquipmentSearch" Text="By Location Code" />
            </div>
            <div style="text-align:center">
                <asp:TextBox ID="SearchIn" runat="server" Width="526px"></asp:TextBox>
                <asp:Button ID="SearchBtn" Text="Search" runat="server" OnClick="SearchBtn_Click"/>
            
            </div>
            <div>
                <asp:Panel runat="server" ID="EquipGridPanel">
                    <div >
                        <asp:Label runat="server">Total: </asp:Label>
                        <asp:Label runat="server" ID="EquipGVCount"></asp:Label>
                    </div>
                    <div style="text-align:center">
                <asp:GridView 
                    ID="EquipGV" 
                    runat="server" 
                    AutoGenerateColumns="false"
                    AutoGenerateSelectButton="true"
                    AutoGenerateEditButton="false"
                    AutoGenerateDeleteButton="false"
                    OnSelectedIndexChanged="EquipGV_SelectedIndexChanged" >
                    <Columns>
                        <asp:BoundField DataField="eID" HeaderText="ID"/>
                        <asp:BoundField DataField="eCode" HeaderText="Code"/>
                        <asp:BoundField DataField="eName" HeaderText="Name"/>
                        <asp:BoundField DataField="ItemCode" HeaderText="Sub Items"/>
                        <asp:BoundField DataField="LocationID" HeaderText="Location"/>
                        <asp:BoundField DataField="eFunction" HeaderText="Function" />
                        <asp:BoundField DataField="eTraining" HeaderText="Training Requirements"/>
               
                    </Columns>
                </asp:GridView>
            </div>


                </asp:Panel>
            </div>


            <div>
                <asp:FormView 
                    ID="EquipFormView" 
                    DataKeyNames="eID"
                    runat="server"

                    OnModeChanging="EquipFormView_ModeChanging"
                    OnItemUpdating="EquipFormView_ItemUpdating"
   
                    >
                    <ItemTemplate>
                        <h3><%# Eval("eName") %></h3>
                        <asp:Label runat="server" ID="eID" ></asp:Label>
                        <table>
                            <tr>
                                <td>ID</td>
                                <td><%#Eval("eID") %></td>
                            </tr>
                            <tr>
                                <td>Code</td>
                                <td><%#Eval("eCode") %></td>
                            </tr>
                            <tr>
                                <td>Name</td>
                                <td><%#Eval("eName") %></td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td><%#Eval("eDesc") %></td>
                            </tr>
                            <tr>
                                <td>Function</td>
                                <td><%#Eval("eFunction") %></td>
                            </tr>
                            <tr>
                                <td>Manual</td>
                                <td><%#Eval("eManual") %></td>
                            </tr>
                            <tr>
                                <td>Safety Caution</td>
                                <td><%#Eval("eSafety") %></td>
                            </tr>
                            <tr>
                                <td>Training Requirement</td>
                       
                                <td><asp:CheckBox 
                                    runat="server" 
                                    AutoPostBack="True"
                                    Enabled="false"
                                    Checked='<%# Convert.ToInt32( Eval("eTraining")).Equals(1) %>'
                                    />
                               
                                </td>
                  
                            </tr>
                            <tr>
                                <td><asp:LinkButton ID="Add" runat="server" Text="New" CommandName="Add"/></td>
                                <td><asp:LinkButton ID="EditBtn" runat="server" Text="Edit" CommandName="Edit"/></td>
                                <td><asp:LinkButton ID="Delete" runat="server" Text="Delete" CommandName="Delete" /></td>
                    
                            </tr>
                        </table>
                    </ItemTemplate> 
                    <EditItemTemplate>
                        <h3><%# Eval("eName") %></h3>
                        <asp:Label runat="server" ID="eIDD" ></asp:Label>
                        <table>
                            <tr>
                                <td>ID</td>
                                <td><asp:Label ID="eIDLabel" runat="server" Text='<%#Eval("eID")%>'></asp:Label> </td>
                            </tr>
                            <tr>
                                <td>Code</td> 
                                <td><asp:TextBox ID="eCodeUpdateTextBox" runat="server" Text='<%#Bind("eCode") %>'></asp:TextBox> </td>
                            </tr>
                            <tr>
                                <td>Name</td>
                                <td><asp:TextBox ID="eNameUpdateTextBox" runat="server" Text='<%#Bind("eName") %>'></asp:TextBox></td>
                            </tr>
                            <tr>
                                <td>Description</td>
                                <td><asp:TextBox ID="eDescUpdateTextBox" runat="server" Text='<%#Bind("eDesc") %>'></asp:TextBox> </td>
                            </tr>
                            <tr>
                                <td>Function</td>
                                <td><asp:TextBox ID="eFunctionUpdateTextBox" runat="server" Text='<%#Bind("eFunction") %>'></asp:TextBox> </td>
                            </tr>
                            <tr>
                                <td>Manual</td>
                                <td><asp:TextBox ID="eManualUpdateTextBox" runat="server" Text='<%#Bind("eManual") %>'></asp:TextBox></td>
                            </tr>
                            <tr>
                                <td>Safety Caution</td>
                                <td><asp:TextBox ID="eSafetyUpdateTextBox" runat="server" Text='<%#Bind("eSafety") %>'></asp:TextBox></td>
                            </tr>
                            <tr>
                                <td>Training Requirement</td>
          
                                <td>
                                    <asp:CheckBox 
                                        ID="eTrainingCheckBox"
                                        runat="server"
                                         AutoPostBack="true"
                                         Enabled="true"
                                         Checked='<%# Convert.ToInt32(Eval("eTraining")).Equals(1) %>'/>
                                </td>
                               
                            </tr>
                            <tr>
                                <td><asp:LinkButton ID="UpdateBtn" runat="server" Text="Update" CommandName="Update"  /></td>
                                <td><asp:LinkButton ID="CancelBtn" runat="server" Text="Cancel" CommandName="Cancel" /></td>
                  
                    
                            </tr>
                        </table>

                    </EditItemTemplate>
       

                </asp:FormView>
            
            <div>
                <asp:Panel runat="server" ID="ItemGridPanel">
                    <div >
                        <asp:Label runat="server">Total: </asp:Label>
                        <asp:Label runat="server" ID="ItemCount"></asp:Label>
                    </div>

                    <div>
                        <asp:GridView 
                        runat="server"
                        ID="ItemGV"
                        AllowPaging="false" 
                        AutoGenerateColumns="false"
                        DataKeyNames="itemID" 
                        AutoGenerateSelectButton="true"
                        OnSelectedIndexChanged="ItemGV_SelectedIndexChanged" 
                        ShowFooter="true">
                        <Columns>

                            <asp:BoundField HeaderText="ID" DataField="itemID"/>
                            <asp:BoundField HeaderText="Equipment ID" DataField="eID" />
                            <asp:BoundField HeaderText="Code" DataField="itemCode"/>
                            <asp:BoundField HeaderText="Status" DataField="itemStatus" />
                            <asp:BoundField HeaderText="Location" DataField="locID"/>
                            <asp:BoundField HeaderText="Delivery Date" DataField="itemDeliveryDate"/>
                   
                            <asp:TemplateField HeaderText="Removal Date">
                                <ItemTemplate>
                                    <asp:Label runat="server" ID="RemovalDateLbl" Text='<%# Eval("itemRemovalDate")%>'></asp:Label>
                                </ItemTemplate>
                                <FooterTemplate>
                                    <asp:LinkButton runat="server" ID="AddItemBtn" OnClick="AddItemBtn_Click" Text="Add"></asp:LinkButton>
                                </FooterTemplate>
                            </asp:TemplateField>
                        </Columns> 
               
                    </asp:GridView>
                    </div>
                </asp:Panel>
            </div>

            <div>
                <asp:FormView 
                runat="server" 
                ID="ItemFV"
                DataKeyNames="itemID"
                OnItemInserting="ItemFV_ItemInserting"
                OnModeChanging="ItemFV_ModeChanging"
                OnItemDeleting="ItemFV_ItemDeleting"
               >
                <ItemTemplate>
                    <table>
                
                        <tr>
                            <td>ID</td>
                            <td>
                                <asp:Label runat="server" Text='<%# Eval("itemID")%>'></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td>Equipment ID</td>
                            <td>
                                <asp:Label runat="server" Text='<%# Eval("eID") %>' ID="eIDLabel"></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td>Code</td>
                            <td>
                                <asp:Label runat="server" Text='<%# Eval("itemCode") %>'></asp:Label>
                            </td>
                        </tr>
                        <tr>
                            <td>Status</td>
                            <td><asp:Label runat="server" Text='<%# Eval("itemStatus") %>'></asp:Label></td>
                        </tr>
                        <tr>
                            <td>Location</td>
                            <td><asp:Label runat="server" Text='<%# Eval("locID") %>'></asp:Label></td>
                        </tr>
                        <tr>
                            <td>Delivery Date</td>
                            <td><asp:Label runat="server" Text='<%# Eval("itemDeliveryDate") %>'></asp:Label></td>
                        </tr>
                        <tr>
                            <td>Removal Date</td>
                            <td><asp:Label runat="server" Text='<%# Eval("itemRemovalDate") %>'></asp:Label></td>
                        </tr>
                        <tr>
                            <td>
                                <asp:LinkButton runat="server" Text="Add" CommandName="New"></asp:LinkButton>
                            </td>
                            <td>
                                <asp:LinkButton runat="server" Text="Delete" 
                                    CommandName="Delete" ></asp:LinkButton>
                            </td>
                            
                        </tr>
                    </table>
                </ItemTemplate>
                <InsertItemTemplate>
                    <table>
                        <tr>
                            <td>
                                <h1>Add Equipment Item</h1>
                            </td>
                        </tr>
                
                        
                        <tr>
                            <td>Equipment ID</td>
                            <td>
                                <asp:TextBox runat="server" ID="eIDTextBox" TextMode="Number" Text='<%# Eval(EquipFormView.DataKey.Value.ToString()) %>'
                                    ></asp:TextBox>
                            </td>
                        </tr>
                    

                        <tr>
                            <td>Status</td>
                            <td><asp:TextBox runat="server" ID="itemStatusTextBox" ></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Location</td>
                            <td><asp:TextBox runat="server" ID="locIDTextBox"></asp:TextBox></td>
                        </tr>
                        <tr>
                            <td>Delivery Date</td>
                            
                             <asp:UpdatePanel runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
                                    <ContentTemplate>
                                        <asp:Calendar runat="server" ID="DeliveryDateCalendar"></asp:Calendar>
                                    </ContentTemplate>
                                </asp:UpdatePanel>
                        </tr>
                        <tr>
                            <td>Removal Date</td>
                            
                            <asp:UpdatePanel runat="server" ChildrenAsTriggers="false" UpdateMode="Conditional">
                                <ContentTemplate>
                                    <asp:Calendar runat="server" ID="RemovalDateCalendar"></asp:Calendar>
                                </ContentTemplate>
                            </asp:UpdatePanel>
                            
                        </tr>
                        <tr>
                            <td>
                                <asp:LinkButton runat="server" CommandName="Insert" Text="Submit"></asp:LinkButton>
                            </td>
                        </tr>
                    </table>

                </InsertItemTemplate>
            </asp:FormView>
            </div>
            



        </ContentTemplate>
    </asp:UpdatePanel>

   
</asp:Content>
