<%@ Page Title="Equipment" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Equipment.aspx.cs" Inherits="Makerspace.Equipment" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
       <h1>Makerspace Equipment</h1>
   </div>
    <div id="CategoryMenu" style="text-align:center">

        <asp:ListView ID="categoryList" runat="server" DataSourceID="MakerspaceDB">
            <ItemTemplate>
                    <b style="font-size: large; font-style: normal">
                        <asp:Button  ID="cat_btn" runat="server" Text='<%# Eval("catName")%>'>   
                        </asp:Button> 
                    </b>
                </ItemTemplate>
                <ItemSeparatorTemplate>  |  </ItemSeparatorTemplate>
        </asp:ListView>

        <asp:SqlDataSource ID="MakerspaceDB" runat="server" ConnectionString="<%$ ConnectionStrings:MakerspaceDBConnectionString %>" SelectCommand="SELECT [catName] FROM [EquipmentCategory]">
        </asp:SqlDataSource>


        <br />
        <asp:RadioButton ID="RadioButton3" runat="server" GroupName="EquipmentSearch" Text="Equipment Name" />
        <asp:RadioButton ID="RadioButton2" runat="server" GroupName="EquipmentSearch" OnCheckedChanged="RadioButton2_CheckedChanged" Text="Equipment Function" />
        <asp:RadioButton ID="RadioButton4" runat="server" GroupName="EquipmentSearch" Text="Equipment Location" />
        <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
        <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="Search" style="width: 67px" />
        <asp:GridView ID="GridView1" runat="server"
            BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" 
            AutoGenerateDeleteButton ="True"
            OnRowDeleting ="GridView1_RowDeleting"
      
            >
   
            <FooterStyle BackColor="White" ForeColor="#000066" />
            <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
            <RowStyle ForeColor="#000066" />
            <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="#007DBB" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#00547E" />
        </asp:GridView>


        <asp:FormView ID="FormView1" runat="server">
        </asp:FormView>


        <asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="New" />


        <br />
        <table class="nav-justified">
            <tr>
                <td style="height: 20px; width: 549px">Equipment code</td>
                <td style="height: 20px; width: 136px;">
                    <asp:TextBox ID="TextBox2" runat="server"  Width="448px" AutoCompleteType="Disabled"></asp:TextBox>
                </td>
                <td style="height: 20px"></td>
            </tr>
            <tr>
                <td style="width: 549px">Equipment name</td>
                <td style="width: 136px">
                    <asp:TextBox ID="TextBox3" runat="server" Width="447px" ></asp:TextBox>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 549px; height: 22px;">Description</td>
                <td style="width: 136px; height: 22px">
                    <asp:TextBox ID="TextBox4" runat="server" Width="449px"></asp:TextBox>
                </td>
                <td style="height: 22px"></td>
            </tr>
            <tr>
                <td style="width: 549px">Function</td>
                <td style="width: 136px">
                    <asp:TextBox ID="TextBox5" runat="server" Width="449px"></asp:TextBox>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 549px">Manual</td>
                <td style="width: 136px">
                    <asp:TextBox ID="TextBox6" runat="server" Width="448px"></asp:TextBox>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 549px">Safety</td>
                <td style="width: 136px">
                    <asp:TextBox ID="TextBox7" runat="server" Width="448px"></asp:TextBox>
                </td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td style="width: 549px">Training</td>
                <td style="width: 136px">
                    <asp:CheckBox ID="CheckBox1" runat="server" />
                </td>
                <td>&nbsp;</td>
            </tr>
        </table>


        <br />


        <asp:Button ID="Button4" runat="server" OnClick="Button4_Click" Text="Add new" />


        <br />

    </div>

</asp:Content>
