------FIRST, DROP CONSTRAINT FROM DEPENDENT --> INDEPENDENT OBJECTS------

ALTER TABLE EquipmentItem
DROP CONSTRAINT equipItemPK;

ALTER TABLE EquipmentItem
DROP CONSTRAINT EI_equipementFK;

ALTER TABLE Equipment
DROP CONSTRAINT ePK;


---- MODIFY DATA TYPE---
ALTER TABLE Equipment 
ALTER COLUMN eID CHAR(16);

ALTER TABLE EquipmentItem 
ALTER COLUMN eID CHAR(16);


ALTER TABLE UserTraining
ALTER COLUMN eID CHAR(16);

--- ADD CONSTRAINTS BACK FROM INDEPENDENT TO DEPENDENT OBJECTS ---
ALTER TABLE Equipment
ADD CONSTRAINT ePK UNIQUE(eID);




