/*Role Permission*/
CREATE TABLE Role(
	roleID INT IDENTITY(1,1) PRIMARY KEY,
	roleName NVARCHAR(60)
);
/*permission*/
CREATE TABLE UserRoles(
	userID INT,
	roleID INT,
	CONSTRAINT userID FOREIGN KEY (userID) REFERENCES MksUser (userID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT roleID FOREIGN KEY (roleID) REFERENCES Role (roleID) ON DELETE CASCADE ON UPDATE CASCADE

);