INSERT INTO Equipment VALUES ('A18-030', ' CNC Router ', 'CNC Router VE11325V', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-032', ' 3D Scanner ', 'EinScan Pro 2X Plus with R2 function', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-033', '3D Printer', 'Prusa i3 MK3S', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-034', ' 3D Printer ', 'Prusa i3 MK3S', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-035', ' Laser cutter ', 'Epilog Mini 24', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-036', ' Soldering Iron ', 'High Quality Soldering Irons WSD 81i, 230V', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-037', ' Fluorescent Magnifier Lamp ', 'Fluorescent Magnifier Lamp', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-038', ' Inspection microscope ', '3.5X-90X Stereo Zoom Microscope on Boom Stand with 80 LED Light Included', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-039', ' Oscilloscope ', 'Siglent SDS1104X-E Plus with 16 Digital channel and Serial Trigger & Decode', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-040', ' 4-in-1 Rework station ', 'Rework station all in one SL916
Soldering and Desoldring iron station', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-041', 'Hot air rework station SS-968B', 'Hot air rework station SS-968B', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-042', ' Power supply ', 'DC Power supply SPD1305X', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-043', ' Smoke filter ', 'Fume Extractor SS-593B', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-046', 'Vertical band saw', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-047', ' Sliding compound miter saw ', 'DeWalt DWS780', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-048', ' Drill press(es) ', 'Drill press HK-KD 800', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-050', ' Sander ', 'Belt and Disc Sander AS406', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-051', 'Shop Vac', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-052', 'Air cleaner', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-053', 'Vacuum Cleaner', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-054', ' Hot wire foam cutter ', 'Proxxon 37080', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-055', ' Fume extractor ', 'Sentry Air Systems SS-300-WFE', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-056', ' Dremel tool set ', 'Dremel rotary tool with workstation and keyless chuck 3000', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-057', ' Foredom dremel tool ', 'Foredom tool M.SR-FCT', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-058', 'Foredom handpiece', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-060', ' Tool storage cabinets ', 'Drawer Mobile Tool Trolley GREENTCAC0701', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-061', 'Sturdy table for 3D printer', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-067', ' Air compressor ', 'Air compressor  Pegasus, 330L, 230V', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-070', ' Pallet Jack ', 'Pallet Jack HPT25M', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-072', ' Projector  (for makerspace) ', 'SONY VPL-DX241', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-073', ' Projector screen (for makerspace) ', 'Projection Screen 100 Inch ', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-074', ' Color laser printer (for makerspace) ', 'Canon imageCLASS MF 746Cx', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-075', ' Large format printer (color) (for makerspace) ', 'Canon imagePROGRAF TX-5400, 44 inch printer', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-076', ' Sewing machine ', 'Sewing machine brother GS2700', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-077', ' Serger ', 'Brother 2104D Overlocker (2-Needles 3/4-Threads Overlock Machine)', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-078', ' Vinyl Cutter ', 'Vinyl Cutter Cutting Plotter CAMM-1 GS-24', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-079', 'Screen printing hinge clamps', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-080', 'Screen printing screens (pk of 6)', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-105-1', ' Darkroom ', 'Beseler 67XLC Condenser Enlarger with Lens Kit, 230V (Black & White)', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-105-18', ' Darkroom ', 'GraLab Model 300 Electro-Mechanical Darkroom Timer - 120V/60/Hz', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-105-20', ' Darkroom ', 'Logan Electric 8 x 10" Desk Top Light Box #810 with One 5000K (Color-corrected) Lamp', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-105-22', ' Darkroom ', 'Dahle 552 Professional Rolling Trimmer (20-1/8")', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-109', 'PCB Prototyping Eleven Lab', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-110', 'Milling Kit', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-111', 'PCB 01 layer and 02 layer, size 20x30cm, pack 50pcs', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-112', 'Pick and place CNC LitePlacer', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-113', 'Stencil Printer', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-114', 'Reflow Oven ', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-115', 'Solder Paste and tools', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-116', 'Desktop Digital Multimeter  (SDM3045X0', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-117', 'Spectrum analyzer Siglent SSA3032 X-TG', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-118', 'Function Generator', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-119', 'Heavy-Duty Benchtop English Wheel', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-120', 'SciLab Forced-air Ovens, 105 Lit', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-121', 'Furnaces, WiseTherm FSC” 1,450C Programmable High-Temp', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-122', 'Digital scale, Ohaus T31P', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-123', 'Digital scale, JWL-15K', '', '', '', 0, 1);
INSERT INTO Equipment VALUES ('A18-124', 'Digital scale, TPS20MTB', '', '', '', 0, 1);


