INSERT INTO UserRoles VALUES(1,1);
INSERT INTO UserRoles VALUES(2,2);
INSERT INTO UserRoles VALUES(3,1);
INSERT INTO UserRoles VALUES(4,2);
INSERT INTO UserRoles VALUES(5,2);
INSERT INTO UserRoles VALUES(6,1);